export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_ENTIRE_ITEM = "REMOVE_ENTIRE_ITEM";
export const ADD_NOTE_TO_ITEM = "ADD_NOTE_TO_ITEM";

export const products = [
  {
    id: 1,
    title: "Pullover with pattern",
    price: "599",
    category: "men",
    brand: "Fancy Brand",
    category: "men",
    rating: "56 ratings",
    image: [
      "https://images.unsplash.com/flagged/photo-1571366992791-2ad2078656cb?auto=format&q=75&fit=crop&w=250",
      "https://images.unsplash.com/flagged/photo-1571366992968-15b65708ee76?auto=format&q=75&fit=crop&w=250",
      "https://images.unsplash.com/flagged/photo-1571366992999-47669b775ef6?auto=format&q=75&fit=crop&w=250`",
    ],
  },
  {
    id: 2,
    title: "Men Regular Fit Solid Button Down Collar Formal Shirt",
    price: "494",
    category: "men",
    brand: "Deemon",
    rating: "39 ratings",
    image: [
      "/images/shirt/shirt1.jpg",
      "/images/shirt/shirt1.1.jpg",
      "/images/shirt/shirt1.2.jpg",
    ],
  },
  {
    id: 3,
    title: "Men Regular Fit Solid Button Down Collar Formal Shirt",
    price: "499",
    category: "men",
    brand: "Vebnor",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt2.webp",
      "/images/shirt/shirt2.1.webp",
      "/images/shirt/shirt2.2.webp",
    ],
  },
  {
    id: 4,
    title: "Men Slim Fit Striped Casual Shirt",
    price: "389",
    category: "men",
    brand: "FUBAR",
    rating: "37 ratings",
    image: [
      "/images/shirt/shirt3.webp",
      "/images/shirt/shirt3.1.webp",
      "/images/shirt/shirt3.2.webp",
    ],
  },
  {
    id: 5,
    title: "Men Regular Fit Self Design Button Down Collar Casual Shirt",
    price: "394",
    category: "men",
    brand: "DIMMY",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt4.webp",
      "/images/shirt/shirt4.1.webp",
      "/images/shirt/shirt4.2.webp",
    ],
  },
  {
    id: 6,
    title: "Men Regular Fit Striped Casual Shirt",
    price: "299",
    category: "men",
    brand: "COMBRAIDED",
    rating: "42 ratings",
    image: [
      "/images/shirt/shirt5.webp",
      "/images/shirt/shirt5.1.webp",
      "/images/shirt/shirt5.2.webp",
    ],
  },
  {
    id: 7,
    title: "Men Slim Fit Solid Spread Collar Casual Shirt",
    price: "857",
    category: "men",
    brand: "KILLER ",
    rating: "49 ratings",
    image: [
      "/images/shirt/shirt7.webp",
      "/images/shirt/shirt7.1.webp",
      "/images/shirt/shirt7.2.webp",
    ],
  },
  {
    id: 8,
    title: "Men Slim Fit Solid Spread Collar Casual Shirt",
    price: "857",
    category: "men",
    brand: "KILLER ",
    rating: "49 ratings",
    image: [
      "/images/shirt/shirt8.webp",
      "/images/shirt/shirt8.1.webp",
      "/images/shirt/shirt8.2.webp",
    ],
  },
  {
    id: 9,
    title: "Men Slim Fit Solid Spread Collar Casual Shirt",
    price: "955",
    category: "men",
    brand: "DIMMY  ",
    rating: "49 ratings",
    image: [
      "/images/shirt/shirt9.webp",
      "/images/shirt/shirt9.1.webp",
      "/images/shirt/shirt9.2.webp",
    ],
  },
  {
    id: 10,
    title: "Men Slim Fit Solid Spread Collar Casual Shirt",
    price: "857",
    category: "men",
    brand: "KILLER ",
    rating: "49 ratings",
    image: [
      "/images/shirt/shirt7.webp",
      "/images/shirt/shirt7.1.webp",
      "/images/shirt/shirt7.2.webp",
    ],
  },
  {
    id: 11,
    title: "Women Gown Multicolor Dress",
    price: "389",
    category: "men",
    brand: "METRONAUT  ",
    rating: "43 ratings",
    image: [
      "/images/shirt/shirt10.webp",
      "/images/shirt/shirt10.1.webp",
      "/images/shirt/shirt10.2.webp",
    ],
  },
  {
    id: 12,
    title: "Women Fit and Flare Maroon Dress",
    price: "495",
    category: "women",
    brand: "Presha",
    rating: "41 ratings",
    image: [
      "/images/shirt/shirt11.webp",
      "/images/shirt/shirt11.1.webp",
      "/images/shirt/shirt11.2.webp",
    ],
  },
  {
    id: 13,
    title: "Women Fit and Flare Light Green Dress",
    price: "499",
    category: "women",
    brand: "Akshara Fashion",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt12.webp",
      "/images/shirt/shirt12.1.webp",
      "/images/shirt/shirt12.2.webp",
    ],
  },
  {
    id: 14,
    title: "Women A-line Beige, Black, Red Dress",
    price: "389",
    category: "women",
    brand: "METRONAUT ",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt12.webp",
      "/images/shirt/shirt12.1.webp",
      "/images/shirt/shirt12.2.webp",
    ],
  },
  {
    id: 15,
    title: "Women A-line Beige, Black, Red Dress",
    price: "389",
    category: "women",
    brand: "METRONAUT ",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt14.webp",
      "/images/shirt/shirt14.1.webp",
      "/images/shirt/shirt14.2.webp",
    ],
  },
  {
    id: 16,
    title: "Women Tiered Yellow, Light Green Dress",
    price: "1049",
    category: "women",
    brand: "Janasya  ",
    rating: "41 ratings",
    image: [
      "/images/shirt/shirt15.webp",
      "/images/shirt/shirt15.1.webp",
      "/images/shirt/shirt15.2.webp",
    ],
  },
  {
    id: 17,
    title: "Women Maxi White Dress",
    price: "649",
    category: "women",
    brand: "FLORINEST   ",
    rating: "38 ratings",
    image: [
      "/images/shirt/shirt16.webp",
      "/images/shirt/shirt16.1.webp",
      "/images/shirt/shirt16.2.webp",
    ],
  },
  {
    id: 18,
    title: "Women Fit and Flare Black Dress",
    price: "729",
    category: "women",
    brand: "Yogiraj Enterprise",
    rating: "37 ratings",
    image: [
      "/images/shirt/shirt17.webp",
      "/images/shirt/shirt17.1.webp",
      "/images/shirt/shirt17.2.webp",
    ],
  },
  {
    id: 19,
    title: "Women Ethnic Dress Yellow Dress",
    price: "799",
    category: "women",
    brand: "KRULRIN ",
    rating: "38 ratings",
    image: [
      "/images/shirt/shirt18.webp",
      "/images/shirt/shirt18.1.webp",
      "/images/shirt/shirt18.2.webp",
    ],
  },
  {
    id: 20,
    title: "Women Ethnic Dress Maroon Dress",
    price: "1,179",
    category: "women",
    brand: "Vishudh",
    rating: "39 ratings",
    image: [
      "/images/shirt/shirt19.webp",
      "/images/shirt/shirt19.1.webp",
      "/images/shirt/shirt19.2.webp",
    ],
  },
  {
    id: 21,
    title: "Women Fit and Flare Dark Blue, Brown, White Dress",
    price: "425",
    category: "women",
    brand: "Fashion2wear",
    rating: "35 ratings",
    image: [
      "/images/shirt/shirt20.webp",
      "/images/shirt/shirt20.1.webp",
      "/images/shirt/shirt20.2.webp",
    ],
  },
  {
    id: 22,
    title: "Women Fit and Flare Multicolor Dress",
    price: "284",
    category: "women",
    brand: "ANBA ",
    rating: "30 ratings",
    image: [
      "/images/shirt/shirt21.webp",
      "/images/shirt/shirt21.1.webp",
      "/images/shirt/shirt21.2.webp",
    ],
  },
  {
    id: 23,
    title: "Women Fit and Flare Light Green Dress",
    price: "432",
    category: "women",
    brand: "NYAARI  ",
    rating: "30 ratings",
    image: [
      "/images/shirt/shirt22.webp",
      "/images/shirt/shirt22.1.webp",
      "/images/shirt/shirt22.2.webp",
    ],
  },
  {
    id: 24,
    title: "Girls Maxi/Full Length Casual Dress  (Pink, 3/4 Sleeve)",
    price: "325",
    category: "women",
    brand: "Aarya Designer",
    rating: "37 ratings",
    image: [
      "/images/shirt/shirt23.webp",
      "/images/shirt/shirt23.1.webp",
      "/images/shirt/shirt23.2.webp",
    ],
  },
  {
    id: 25,
    title: "Girls Calf Length Festive/Wedding Dress  (Pink, 3/4 Sleeve)",
    price: "284",
    category: "women",
    brand: "LUCKY FASHION WORLD",
    rating: "38 ratings",
    image: [
      "/images/shirt/shirt23.webp",
      "/images/shirt/shirt23.1.webp",
      "/images/shirt/shirt23.2.webp",
    ],
  },
  {
    id: 26,
    title: "Girls Calf Length Festive/Wedding Dress  (Pink, 3/4 Sleeve)",
    price: "284",
    category: "women",
    brand: "LUCKY FASHION WORLD",
    rating: "38 ratings",
    image: [
      "/images/shirt/shirt24.webp",
      "/images/shirt/shirt24.1.webp",
      "/images/shirt/shirt24.2.webp",
    ],
  },
  {
    id: 27,
    title: "Girls Below Knee Party Dress  (Pink, 3/4 Sleeve)",
    price: "237",
    category: "women",
    brand: "MILILIAM ",
    rating: "38 ratings",
    image: [
      "/images/shirt/shirt25.webp",
      "/images/shirt/shirt25.1.webp",
      "/images/shirt/shirt25.2.webp",
    ],
  },
  {
    id: 28,
    title: "Girls Calf Length Party Dress  (Green, 3/4 Sleeve)",
    price: "299",
    category: "women",
    brand: "MODERN DREAM",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt26.webp",
      "/images/shirt/shirt26.1.webp",
      "/images/shirt/shirt26.2.webp",
    ],
  },
  {
    id: 29,
    title: "Girls Below Knee Party Dress  (Black, Full Sleeve)",
    price: "429",
    category: "women",
    brand: "Zenat   ",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt27.webp",
      "/images/shirt/shirt27.1.webp",
      "/images/shirt/shirt27.2.webp",
    ],
  },
  {
    id: 30,
    title: "Girls Maxi/Full Length Festive/Wedding Dress  (Maroon, 3/4 Sleeve)",
    price: "659",
    category: "women",
    brand: "Fashion Dream",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt28.webp",
      "/images/shirt/shirt28.1.webp",
      "/images/shirt/shirt28.2.webp",
    ],
  },
  {
    id: 31,
    title: "Girls Below Knee Party Dress  (Pink, Fashion Sleeve)",
    price: "249",
    category: "women",
    brand: "SK Dresses",
    rating: "41 ratings",
    image: [
      "/images/shirt/shirt29.webp",
      "/images/shirt/shirt29.1.webp",
      "/images/shirt/shirt29.2.webp",
    ],
  },
  {
    id: 32,
    title: "Girls Below Knee Festive/Wedding Dress  (Red, Sleeveless)",
    price: "391",
    category: "women",
    brand: "ULTINITY",
    rating: "41 ratings",
    image: [
      "/images/shirt/shirt30.webp",
      "/images/shirt/shirt30.1.webp",
      "/images/shirt/shirt30.2.webp",
    ],
  },
  {
    id: 33,
    title: "Boys Casual Sweatshirt Track Pants  (White, Black)",
    price: "391",
    category: "men",
    brand: "TOONYPORT ",
    rating: "48 ratings",
    image: [
      "/images/shirt/shirt31.webp",
      "/images/shirt/shirt31.1.webp",
      "/images/shirt/shirt31.2.webp",
    ],
  },
  {
    id: 34,
    title: "Boys & Girls Casual T-shirt Pant  (Blue)",
    price: "299",
    category: "men",
    brand: "KIDSDOM ",
    rating: "37 ratings",
    image: [
      "/images/shirt/shirt32.webp",
      "/images/shirt/shirt32.1.webp",
      "/images/shirt/shirt32.2.webp",
    ],
  },
  {
    id: 35,
    title: "Boys Casual T-shirt Track Pants  (RED)",
    price: "349",
    category: "men",
    brand: "KEESOR",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt33.webp",
      "/images/shirt/shirt33.1.webp",
      "/images/shirt/shirt33.1.webp",
    ],
  },
  {
    id: 36,
    title: "Boys Casual T-shirt Pant  (Blue)",
    price: "899",
    category: "men",
    brand: "TOONYPORT ",
    rating: "40 ratings",
    image: [
      "/images/shirt/shirt35.webp",
      "/images/shirt/shirt35.1.webp",
      "/images/shirt/shirt35.2.webp",
    ],
  },
  {
    id: 37,
    title: "Boys & Girls Casual Sweatshirt Sweatpant  (Charcoal Grey)",
    price: "440",
    category: "men",
    brand: "Mars Infiniti",
    rating: "42 ratings",
    image: [
      "/images/shirt/shirt36.webp",
      "/images/shirt/shirt36.1.webp",
      "/images/shirt/shirt36.2.webp",
    ],
  },
  {
    id: 38,
    title: "Boys & Girls Casual Sweatshirt Sweatpant  (Charcoal Grey)",
    price: "440",
    category: "men",
    brand: "Mars Infiniti",
    rating: "42 ratings",
    image: [
      "/images/shirt/shirt37.webp",
      "/images/shirt/shirt37.1.webp",
      "/images/shirt/shirt37.2.webp",
    ],
  },
  {
    id: 39,
    title: "Boys & Girls Party(Festive) T-shirt Track Pants  (White/Green)",
    price: "326",
    category: "men",
    brand: "Afreen Creations ",
    rating: "41 ratings",
    image: [
      "/images/shirt/shirt38.webp",
      "/images/shirt/shirt38.1.webp",
      "/images/shirt/shirt38.2.webp",
    ],
  },
];
